### ISSUE TITLE
segyviewlib installation problem

### ISSUE THREAD

**Issue by ahmedmaalej** [equinor/segyviewer#40]
I get this error while trying to install segyviewer with virtualenviorment using python3, any idea how fix it:

`` pip install segyviewlib==1.1.3
Collecting segyviewlib==1.1.3
ERROR: segyviewer 1.1.3 requires segyviewlib, which is not installed.
Installing collected packages: segyviewlib
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ahmed/Documents/Ahmed/Work/Code/Environments/segyio_py3/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/ahmed/Documents/Ahmed/Work/Code/Environments/segyio_py3/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/ahmed/Documents/Ahmed/Work/Code/Environments/segyio_py3/lib/python3.5/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/ahmed/Documents/Ahmed/Work/Code/Environments/segyio_py3/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 920, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/ahmed/Documents/Ahmed/Work/Code/Environments/segyio_py3/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/ahmed/Documents/Ahmed/Work/Code/Environments/segyio_py3/lib/python3.5/site-packages/pip/_internal/wheel.py", line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: segyviewlib==1.1.3 .dist-info directory not found``

**Comment by jokva** [comment]
Hi,

This project is not really under development, and python 3 support was never implemented. @lars-petter-hauge has a patch https://github.com/equinor/segyviewer/pull/38 but it was never really completed, and it hasn't been a priority with us I'm afraid. If you figure out what's necessary to fix it, we'll happily accept a pull request.
